### PR TITLE
Fix softether src cloning

### PR DESCRIPTION
**Pull request by dormancygrace**

### CODE REVIEW

**Comment by cenk1cenk2** [comment]
Hey sorry my stupidity but isnt we suppose to use apt-get on terminals since it has the better terminal interface?

**Comment by dormancygrace** [comment]
> Hey sorry my stupidity but isnt we suppose to use apt-get on terminals since it has the better terminal interface?

Yeah, it's my stupidity, sorry

**Comment by cenk1cenk2** [comment]
Na i dint mean it like that since I couldnt make my mind up even after googleing for a bit and was just confused. Just had that in the back of my mind.

**Comment by dormancygrace** [comment]
> Na i dint mean it like that since I couldnt make my mind up even after googleing for a bit and was just confused. Just had that in the back of my mind.

It's totally right, so yes, we need to use apt-get.

What you think about doing go-built deps in container also?

**Comment by cenk1cenk2** [comment]
> > Na i dint mean it like that since I couldnt make my mind up even after googleing for a bit and was just confused. Just had that in the back of my mind.
> 
> It's totally right, so yes, we need to use apt-get.
> 
> What you think about doing go-built deps in container also?

I would like to keep it seperate to have some standardization accross my repositories if that is no problem.

**Comment by dormancygrace** [comment]
Your project - your rules ) but with that style there is need of go binaries installation on host machine. In my opinion it breaks main concept of containers

**Comment by cenk1cenk2** [comment]
I can agree on that part where it is more like an application that has made in to a container rather than a container which is the intend of this project.

But i can turn a blind eye on that for having the convience of centerally controlling how an golang app is built.

**Comment by dormancygrace** [comment]
I think, there is a way, to make logs of building inside container, make available where you need them )

**Pull request merged**
